<x-office-layout>
    <x-slot name="menu_active">
        {{ __('attendance') }}
    </x-slot>
    <x-slot name="head_slot">
        <link href="{{ asset('asset/css/attendance.css') }}" rel="stylesheet">
    </x-slot>

    <div class="title-content">
        <h2>Attendance</h2>
    </div>

    <div class="body-content scrollable-container rounded-4 p-5">
        <div class="attendance-container">
            <!-- Left Section - User Profile -->
            <div class="attendance-left">
                <div class="profile-image-container">
                    <img src="{{ $employee && $employee->profile_picture ? asset($employee->profile_picture) : asset('asset/img/default-profile.png') }}"
                        alt="User Profile" class="profile-image">
                </div>
                <div class="user-info">
                    <h3 class="user-name">{{ $employee ? $employee->name : 'User Name' }}</h3>
                    <p class="user-email">{{ $employee ? $employee->email_work : 'user@example.com' }}</p>
                    <p class="user-division">
                        @if ($employee && $employee->division)
                            {{ $employee->division->name_division }}
                        @else
                            <span style="color:red;">Division not assigned</span>
                        @endif
                    </p>
                </div>
                <div class="attendance-actions-left mt-4 w-100 d-flex justify-content-center">
                    <button class="btn btn-check-in w-50 mb-2" id="checkInBtn" style="display: none;">
                        <span class="material-symbols-outlined">alarm_on</span>
                        Check In
                    </button>
                    <button class="btn btn-check-out w-50 mb-2" id="checkOutBtn" style="display: none;">
                        <span class="material-symbols-outlined">alarm_off</span>
                        Check Out
                    </button>
                    <input type="hidden" id="checkInTime" name="checkInTime" value="">
                    <input type="hidden" id="checkOutTime" name="checkOutTime" value="">
                </div>
            </div>

            <!-- Right Section - Calendar -->
            <div class="attendance-right">
                <div class="calendar-container">
                    <div class="calendar-header">
                        <button class="btn btn-sm" id="prevMonth">
                            <i class="fas fa-chevron-left"></i>
                        </button>
                        <h4 id="currentMonthYear">July 2024</h4>
                        <button class="btn btn-sm" id="nextMonth">
                            <i class="fas fa-chevron-right"></i>
                        </button>
                    </div>

                    <div class="calendar-weekdays">
                        <div>Sun</div>
                        <div>Mon</div>
                        <div>Tue</div>
                        <div>Wed</div>
                        <div>Thu</div>
                        <div>Fri</div>
                        <div>Sat</div>
                    </div>

                    <input type="hidden" id="currentDate" name="currentDate" value="">
<!-- Removed attendanceStatus div as status is shown on calendar dates -->
                    <div class="calendar-days" id="calendarDays">
                        <!-- Calendar days will be generated by JavaScript -->
                    </div>

                  
                </div>
            </div>
        </div>
    </div>

    <!-- Modal for Check In -->
    <div class="modal fade" id="checkInModal" tabindex="-1" aria-labelledby="checkInModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content rounded-4">
                <div class="modal-header modal-header-custom">
                    <h5 class="modal-title modal-title-custom" id="checkInModalLabel">Check In Attendance</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="checkInForm">
                        <!-- employee_id -->
                        <input type="hidden" name="employee_id" id="employee_id" value="{{ $employee ? $employee->id : '' }}">
                        <!-- is_work_outside -->
                        <div class="mb-3">
                            <label for="is_work_outside" class="form-label">Work Outside</label>
                            <div class="d-flex gap-3">
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="is_work_outside"
                                        id="work_outside_yes" value="1">
                                    <label class="form-check-label" for="work_outside_yes">
                                        Yes
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="is_work_outside"
                                        id="work_outside_no" value="0" checked>
                                    <label class="form-check-label" for="work_outside_no">
                                        No
                                    </label>
                                </div>
                            </div>
                        </div>

                        <!-- date_attendance -->
                        <div class="mb-3">
                            <label for="date_attendance" class="form-label label-custom">Date</label>
                            <input type="date" class="form-control input-text" id="date_attendance"
                                name="date_attendance" readonly>
                        </div>

                        <!-- time_in -->
                        <div class="mb-3">
                            <label for="time_in" class="form-label label-custom">Time In</label>
                            <input type="time" class="form-control input-text" id="time_in" name="time_in"
                                readonly>
                        </div>

                        <!-- time_out -->
                        <div class="mb-3">
                            <label for="time_out" class="form-label label-custom">Time Out</label>
                            <input type="time" class="form-control input-text" id="time_out" name="time_out"
                                readonly>
                        </div>

                        <!-- time_late -->
                        <div class="mb-3">
                            <label for="time_late" class="form-label label-custom">Time Late</label>
                            <input type="text" class="form-control input-text" id="time_late" name="time_late"
                                readonly>
                        </div>

                        <!-- note -->
                        <div class="mb-3">
                            <label for="note" class="form-label label-custom">Note</label>
                            <textarea class="form-control" id="note" name="note" rows="3"></textarea>
                        </div>

                        <!-- image -->
                        <div class="mb-3" id="imageUploadSection">
                            <label class="form-label">Photo</label>
                            <div class="image-upload-container">
                                <label for="imageInput" class="image-upload-label camera-label">
                                    <div class="image-upload-icon">
                                        <i class="fas fa-camera fa-2x text-primary"></i>
                                    </div>
                                    <span id="cameraText">Take Photo with Camera</span>
                                </label>
                                <input type="file" class="form-control d-none" id="imageInput" name="image"
                                    accept="image/*" capture="user">
                                <video id="cameraVideo" autoplay playsinline class="w-50 rounded mt-2"
                                    style="max-height: 250px; display: none;"></video>
                                <canvas id="cameraCanvas" class="d-none"></canvas>
                                <div id="imagePreview" class="image-preview mt-2" style="display: none;">
                                    <img id="previewImg" src="" alt="Preview" class="img-fluid rounded">
                                </div>
                                <button type="button" class="btn btn-sm btn-outline-secondary d-none"
                                    id="clearImageBtn" style="display: none;">
                                    <i class="fas fa-times"></i> Clear
                                </button>
                                <button type="button" class="btn btn-sm btn-primary d-none" id="retakeBtn"
                                    style="display: none;">
                                    <i class="fas fa-redo"></i> Retake
                                </button>
                            </div>
                        </div>

                        <!-- type_attendance -->
                        <input type="hidden" id="type_attendance" name="type_attendance" value="check_in">
                    </form>
                </div>
                <div class="modal-footer modal-footer-custom">
                    <button type="submit" class="btn btn-primary" id="submitCheckInBtn">
                        <span class="material-symbols-outlined">
                            alarm_on
                        </span>
                        Check In
                    </button>
                </div>

            </div>
        </div>
    </div>

    <x-slot name="script_slot">
        <script src="{{ asset('asset/js/attendance.js') }}"></script>
    </x-slot>
</x-office-layout>
